DROP TABLE IF EXISTS driver;

CREATE TABLE driver (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
);

INSERT INTO driver (FIRST_NAME, LAST_NAME) VALUES ('James','Gosling');
INSERT INTO driver (FIRST_NAME, LAST_NAME) VALUES ('Jon','Snow');
INSERT INTO driver (FIRST_NAME, LAST_NAME) VALUES ('Peter','Pan');